# Generated by Django 2.1.7 on 2019-05-26 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', utils.models.RichTextField()),
                ('answer', models.IntegerField()),
                ('choices', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ordering', models.IntegerField()),
                ('difficulty', models.TextField()),
            ],
            options={
                'db_table': 'level_test_problem',
            },
        ),
    ]
