# Generated by Django 2.1.7 on 2019-06-09 02:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_current_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_recommend',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
