# Generated by Django 2.1.7 on 2019-06-09 02:48

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190609_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_reco',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_recommend',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'data'}, null=True),
        ),
    ]
