# Generated by Django 2.1.7 on 2019-06-09 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190609_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_recommend',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_reco',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
