# Generated by Django 2.1.7 on 2019-06-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190609_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommend_round',
            field=models.IntegerField(default=0),
        ),
    ]
