# Generated by Django 2.1.7 on 2019-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bj_username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hr_username',
            field=models.TextField(null=True),
        ),
    ]
