# Generated by Django 2.1.7 on 2019-06-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0003_problemcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('is_Ex', models.BooleanField()),
                ('is_Solved', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to='problem.QuriousDifficulty')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to='problem.Problem')),
                ('problemex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to='problem.ProblemEX')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommend_history',
                'ordering': ('-created_at',),
            },
        ),
    ]
