# Generated by Django 2.1.7 on 2019-06-09 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendhistory',
            old_name='round',
            new_name='round_num',
        ),
        migrations.AlterField(
            model_name='recommendhistory',
            name='is_Ex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendhistory',
            name='is_Solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendhistory',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='recommendhistory',
            name='problemex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendhistory', to='problem.ProblemEX'),
        ),
    ]
