# Generated by Django 2.1.7 on 2019-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemex',
            name='correct_ratio',
            field=models.FloatField(null=True),
        ),
    ]
