# Generated by Django 2.1.7 on 2019-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_problemex_correct_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemex',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
